batch_size: 16
dataset: nyu
experiment_name: shared_decoder_naive_nyu
fine_tune: false
fine_tune_all: false
fine_tune_decoder: true
img_size_h: 240
img_size_w: 320
learning_rate: 0.0001
loss_type: naive loss
model: deeplab_shared_decoder
model_type: multitask
naive_alpha: 0.9
num_epochs: 100
num_workers: 8
test_data: ./NYU_data/nyu_depth_v2_labeled.mat
train_data: ./NYU_data/nyu_depth_v2_labeled.mat
val_data: ./NYU_data/nyu_depth_v2_labeled.mat
version_number: '0.1'
