batch_size: 16
description: 3 steps instead of 5
epoch_milestones: 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
  51, 54, 57
experiment_name: shared_decoder_em
fine_tune: false
fine_tune_all: true
img_size_h: 192
img_size_w: 256
learning_rate: 0.0001
loss_type: naive loss
model: deeplab_shared_decoder
model_type: multitask
naive_alpha: 0.9
num_epochs: 60
num_workers: 8
test_data: ./data/test_data.csv
train_data: ./data/train_data.csv
val_data: ./data/val_data.csv
version_number: '1.2'
