batch_size: 8
dataset: nyu
experiment_name: shared_decoder_naive
fine_tune: false
fine_tune_all: true
img_size_h: 384
img_size_w: 512
learning_rate: 0.0001
loss_type: naive loss
model: deeplab_shared_decoder
model_type: multitask
naive_alpha: 0.9
num_epochs: 100
num_workers: 8
nyu_data: ./NYU_data/nyu_depth_v2_labeled.mat
test_data: ./data/test_data.csv
train_data: ./data/train_data.csv
val_data: ./data/val_data.csv
version_number: '6'
