batch_size: 16
dataset: hypersim
experiment_name: shared_decoder_naive_fix_resnext
fine_tune: false
fine_tune_all: true
img_size_h: 192
img_size_w: 256
learning_rate: 0.0005
loss_type: naive loss
model: deeplab_shared_decoder
model_type: multitask
naive_alpha: 0.9
num_epochs: 40
num_workers: 8
resnext: true
test_data: ./data/test_data.csv
train_data: ./data/train_data.csv
val_data: ./data/val_data.csv
version_number: '0.9_5e-4'
