batch_size: 16
dataset: nyu
experiment_name: shared_decoder_naive_nyu
fine_tune: false
fine_tune_all: true
img_size_h: 240
img_size_w: 320
learning_rate: 0.0001
loss_type: naive loss
model: deeplab_shared_decoder
model_type: multitask
naive_alpha: 0.9
num_epochs: 20
num_workers: 8
test_data: ./NYU_data/test_data.h5
train_data: ./NYU_data/train_data.h5
val_data: ./NYU_data/val_data.h5
version_number: '0.9'
