batch_size: 32
experiment_name: shared_decoder_naive
fine_tune: false
fine_tune_all: true
img_size_h: 192
img_size_w: 256
learning_rate: 0.0001
loss_type: naive loss
model: deeplab_shared_decoder
model_type: multitask
naive_alpha: 0.9
num_epochs: 100
num_workers: 8
test_data: ./data/test_data.csv
train_data: ./data/train_data.csv
val_data: ./data/val_data.csv
version_number: '0.9'
