batch_size: 10
checkpoint_path: /datasets/home/47/747/jechterh/FinalProject/experiment_data/shared_decoder_naive_nyu_transfer_proto/v_0.1/checkpoints/epoch=18-step=21735.ckpt
dataset: nyu
experiment_name: shared_decoder_naive_nyu_transfer_proto
fine_tune: true
fine_tune_all: true
fine_tune_decoder: true
img_size_h: 240
img_size_w: 320
learning_rate: 0.0001
loss_type: proto loss
model: deeplab_shared_decoder
model_type: multitask_prototype
naive_alpha: 0.9
num_epochs: 40
num_workers: 8
resnext: true
test_data: ./data/test_data.csv
train_data: ./data/train_data.csv
val_data: ./data/val_data.csv
version_number: '0.1'
